"use client";

// End-to-end encryption for group chat.
//
// What this guarantees: the server stores ciphertext and sealed envelopes it
// has no key for. Nobody reading the database can read a message — not ops, not
// a stolen backup, not us.
//
// What it does not guarantee, and the UI says so rather than implying
// otherwise: the server ships this very file. A compromised build could leak
// keys. That is true of every in-browser E2EE product, and pretending
// otherwise would be the dishonest part.
//
// Shape of the scheme:
//   · each browser holds an ECDH P-256 identity keypair, private half stored
//     non-extractable in IndexedDB so script cannot read it back out
//   · each group has one AES-GCM 256 key, generated by whoever opens the chat
//   · to let a device in, a holder does ECDH(ephemeral, their public key),
//     derives a wrapping key with HKDF, and seals the group key with AES-GCM
//   · messages are AES-GCM with a fresh 12-byte nonce each time
//
// The ephemeral sender key means sealing for a new member never reuses a
// shared secret, so one leaked envelope cannot open the others.

const DB_NAME = "flouna-e2ee";
const STORE = "keys";
const DEVICE_ID_KEY = "flouna.chat.deviceId";

export type MemberDevice = { userId: string; deviceId: string; publicKey: string };
export type Envelope = {
  userId: string;
  deviceId: string;
  senderKey: string;
  iv: string;
  wrappedKey: string;
};

// ---------- base64 ----------

function toB64(buf: ArrayBuffer): string {
  const bytes = new Uint8Array(buf);
  let s = "";
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]!);
  return btoa(s);
}

function fromB64(s: string): ArrayBuffer {
  const bin = atob(s);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes.buffer;
}

// ---------- key storage ----------
//
// IndexedDB rather than localStorage because it can hold a CryptoKey object
// directly. A key stored that way with extractable=false cannot be exported by
// any script afterwards, including a script injected into this origin later.

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 1);
    req.onupgradeneeded = () => {
      if (!req.result.objectStoreNames.contains(STORE)) req.result.createObjectStore(STORE);
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

function idbGet<T>(key: string): Promise<T | undefined> {
  return openDb().then(
    (db) =>
      new Promise<T | undefined>((resolve, reject) => {
        const tx = db.transaction(STORE, "readonly").objectStore(STORE).get(key);
        tx.onsuccess = () => resolve(tx.result as T | undefined);
        tx.onerror = () => reject(tx.error);
      }),
  );
}

function idbPut(key: string, value: unknown): Promise<void> {
  return openDb().then(
    (db) =>
      new Promise<void>((resolve, reject) => {
        const tx = db.transaction(STORE, "readwrite").objectStore(STORE).put(value, key);
        tx.onsuccess = () => resolve();
        tx.onerror = () => reject(tx.error);
      }),
  );
}

/** True when this browser can do the crypto at all (needs a secure context). */
export function cryptoAvailable(): boolean {
  return (
    typeof window !== "undefined" &&
    typeof indexedDB !== "undefined" &&
    Boolean(window.crypto?.subtle)
  );
}

/** Stable per-browser id. Not a secret — it only addresses envelopes. */
export function deviceId(): string {
  let id = localStorage.getItem(DEVICE_ID_KEY);
  if (!id) {
    const bytes = crypto.getRandomValues(new Uint8Array(16));
    id = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
    localStorage.setItem(DEVICE_ID_KEY, id);
  }
  return id;
}

type IdentityKeys = { privateKey: CryptoKey; publicKey: CryptoKey };

/**
 * This device's identity keypair, created once and kept.
 *
 * The private key is generated with extractable=false, so from the moment it
 * exists no code — ours or anyone's — can read the raw bytes back. It can only
 * be used to derive.
 */
export async function identity(): Promise<IdentityKeys> {
  const stored = await idbGet<IdentityKeys>("identity");
  if (stored?.privateKey && stored?.publicKey) return stored;

  const pair = await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" },
    false, // never extractable
    ["deriveKey", "deriveBits"],
  );
  const keys = { privateKey: pair.privateKey, publicKey: pair.publicKey };
  await idbPut("identity", keys);
  return keys;
}

/** The public half, base64 SPKI, for the server to hand to other members. */
export async function publicKeyB64(): Promise<string> {
  const { publicKey } = await identity();
  return toB64(await crypto.subtle.exportKey("spki", publicKey));
}

// ---------- group key ----------

const groupKeyCache = new Map<string, CryptoKey>();

/** A fresh group key. Extractable, because sealing it for members requires
 *  exporting it — it is protected by the envelope, not by the flag. */
export async function newGroupKey(): Promise<CryptoKey> {
  return crypto.subtle.generateKey({ name: "AES-GCM", length: 256 }, true, [
    "encrypt",
    "decrypt",
  ]);
}

/** Remembers the group key for this cart, in memory and in IndexedDB so a
 *  reload does not need the network to read messages already on screen. */
export async function cacheGroupKey(cartId: string, key: CryptoKey): Promise<void> {
  groupKeyCache.set(cartId, key);
  await idbPut(`group:${cartId}`, key);
}

export async function cachedGroupKey(cartId: string): Promise<CryptoKey | null> {
  const inMemory = groupKeyCache.get(cartId);
  if (inMemory) return inMemory;
  const stored = await idbGet<CryptoKey>(`group:${cartId}`);
  if (stored) groupKeyCache.set(cartId, stored);
  return stored ?? null;
}

/** ECDH → HKDF → a 256-bit AES-KW-style wrapping key for one recipient. */
async function wrappingKey(
  privateKey: CryptoKey,
  theirPublicSpki: ArrayBuffer,
  salt: Uint8Array,
): Promise<CryptoKey> {
  const theirKey = await crypto.subtle.importKey(
    "spki",
    theirPublicSpki,
    { name: "ECDH", namedCurve: "P-256" },
    false,
    [],
  );
  const shared = await crypto.subtle.deriveBits(
    { name: "ECDH", public: theirKey },
    privateKey,
    256,
  );
  // HKDF rather than using the raw ECDH output: the shared secret is not
  // uniformly random, and the info string binds the key to this purpose so the
  // same secret can never be reused for something else later.
  const base = await crypto.subtle.importKey("raw", shared, "HKDF", false, ["deriveKey"]);
  return crypto.subtle.deriveKey(
    {
      name: "HKDF",
      hash: "SHA-256",
      salt: salt as unknown as BufferSource,
      info: new TextEncoder().encode("flouna:group-chat:v1"),
    },
    base,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"],
  );
}

/**
 * Seals the group key for one recipient device.
 *
 * A fresh ephemeral keypair per envelope: the recipient needs only the sender's
 * ephemeral public key to open it, and no two envelopes share a secret.
 */
export async function sealFor(
  groupKey: CryptoKey,
  device: MemberDevice,
): Promise<Omit<Envelope, "userId" | "deviceId">> {
  const ephemeral = await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" },
    true,
    ["deriveBits"],
  );
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const wrapper = await wrappingKey(ephemeral.privateKey, fromB64(device.publicKey), iv);
  const raw = await crypto.subtle.exportKey("raw", groupKey);
  const wrapped = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv: iv as unknown as BufferSource },
    wrapper,
    raw,
  );
  return {
    senderKey: toB64(await crypto.subtle.exportKey("spki", ephemeral.publicKey)),
    iv: toB64(iv.buffer as ArrayBuffer),
    wrappedKey: toB64(wrapped),
  };
}

/** Opens an envelope addressed to this device. Returns null if it is not ours
 *  to open, which is a normal state, not an error. */
export async function openEnvelope(env: {
  senderKey: string;
  iv: string;
  wrappedKey: string;
}): Promise<CryptoKey | null> {
  try {
    const { privateKey } = await identity();
    const iv = new Uint8Array(fromB64(env.iv));
    const wrapper = await wrappingKey(privateKey, fromB64(env.senderKey), iv);
    const raw = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: iv as unknown as BufferSource },
      wrapper,
      fromB64(env.wrappedKey),
    );
    return crypto.subtle.importKey("raw", raw, { name: "AES-GCM", length: 256 }, true, [
      "encrypt",
      "decrypt",
    ]);
  } catch {
    return null;
  }
}

// ---------- messages ----------

export async function encryptMessage(
  key: CryptoKey,
  text: string,
): Promise<{ iv: string; ciphertext: string }> {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ct = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv: iv as unknown as BufferSource },
    key,
    new TextEncoder().encode(text),
  );
  return { iv: toB64(iv.buffer as ArrayBuffer), ciphertext: toB64(ct) };
}

/**
 * Decrypts one message. A failure here is expected rather than exceptional —
 * a message sent before this device was let in cannot be read by it, ever —
 * so it returns null and the UI shows a locked line instead of an error.
 */
export async function decryptMessage(
  key: CryptoKey,
  iv: string,
  ciphertext: string,
): Promise<string | null> {
  try {
    const plain = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: new Uint8Array(fromB64(iv)) as unknown as BufferSource },
      key,
      fromB64(ciphertext),
    );
    return new TextDecoder().decode(plain);
  } catch {
    return null;
  }
}
