import type { CareerPath, SkillProfile, Mentor, LearningPlan, JourneyProgress } from "./types";

export const CAREER_PATHS: CareerPath[] = [
  {
    id: "path-pm",
    slug: "product-management",
    title: "Product Management",
    category: "Product",
    fitScore: 88,
    fitLevel: "Exceptional Fit",
    tagline: "Bridge business strategy, technology, and user experience to shape meaningful products.",
    description:
      "You show strong product intuition, cross-functional empathy, and structured problem-solving. Product Management channels your desire to orchestrate impact without being tied to pure execution.",
    whyFit: [
      "Natural inclination for prioritizing user value over raw output",
      "Strong analytical foundation coupled with articulate communication",
      "Demonstrated ability to synthesize conflicting requirements into clear roadmaps",
    ],
    currentStrengths: [
      "Structured problem breakdown & root-cause analysis",
      "User empathy & requirement elicitation",
      "Strategic clarity & cross-discipline collaboration",
    ],
    skillGaps: [
      "Product analytics & quantitative metrics instrumentation (SQL, Amplitude)",
      "Technical trade-off assessment with engineering leads",
      "Executive stakeholder alignment & pricing strategy",
    ],
    typicalFirstSteps: [
      "Deconstruct one beloved product feature into a 2-page Product Requirement Doc (PRD)",
      "Interview 3 users about their workflow friction points and map user journeys",
      "Connect with a practicing Senior PM to review product case study methodology",
    ],
    projectsToTry: [
      {
        title: "Micro-SaaS Retention Audit",
        description: "Analyze onboarding drop-offs and draft a prioritized experiment hypothesis backlog.",
        timeframe: "1-2 weeks",
      },
      {
        title: "AI Feature PRD & Spec",
        description: "Draft an end-to-end PRD for an intelligent notification system with fallback edge-cases.",
        timeframe: "2 weeks",
      },
    ],
    mentorIds: ["mentor-maya", "mentor-priya"],
    learningPlanSlug: "pm-30-day-foundation",
    salaryRange: "₹18L - ₹45L+",
    demandTrend: "+24% YoY growth in product-led teams",
  },
  {
    id: "path-pd",
    slug: "product-design",
    title: "Product Design",
    category: "Design",
    fitScore: 82,
    fitLevel: "Strong Match",
    tagline: "Craft intuitive, beautiful human experiences that turn complex systems into effortless interactions.",
    description:
      "Your visual sensitivity and spatial awareness pair seamlessly with systems thinking. Product Design gives you the canvas to build tactile, memorable digital interactions.",
    whyFit: [
      "Obsession with typography, interaction ergonomics, and layout harmony",
      "Ability to translate ambiguous user pain into tangible UI components",
      "Interest in modern component tokens and scalable design systems",
    ],
    currentStrengths: [
      "Visual hierarchy & typographic restraint",
      "Component design & state modeling",
      "User feedback synthesis and wireframing",
    ],
    skillGaps: [
      "Micro-interaction prototyping with code-level motion fidelity (Framer Motion / CSS)",
      "Usability benchmarking & accessibility (WCAG AAA contrast & keyboard flows)",
      "Design system governance across multi-brand tokens",
    ],
    typicalFirstSteps: [
      "Audit 5 mobile apps for micro-interaction polish and document findings",
      "Build a minimalist design system token set in Figma",
      "Pair with a design leader to refine a portfolio case study",
    ],
    projectsToTry: [
      {
        title: "Editorial Mobile Interface Redesign",
        description: "Design a high-fidelity 5-screen reading flow with typography focus.",
        timeframe: "1 week",
      },
      {
        title: "Interactive Component Library",
        description: "Create an accessible set of dialog, toast, and composer primitives.",
        timeframe: "2 weeks",
      },
    ],
    mentorIds: ["mentor-rohan"],
    learningPlanSlug: "pd-30-day-foundation",
    salaryRange: "₹16L - ₹40L+",
    demandTrend: "+19% demand for system-aware designers",
  },
  {
    id: "path-se",
    slug: "software-engineering",
    title: "Full-Stack Software Engineering",
    category: "Engineering",
    fitScore: 78,
    fitLevel: "High Alignment",
    tagline: "Build resilient, ultra-fast architectures and high-craft interfaces from database to pixels.",
    description:
      "You appreciate craftsmanship in code, deterministic execution, and end-to-end ownership. Building robust web systems turns your ideas into production reality.",
    whyFit: [
      "High comfort with TypeScript, React, and modular component architectures",
      "Strong debugging instinct and curiosity for distributed systems",
      "Appreciation for sub-second UI performance and clean API contracts",
    ],
    currentStrengths: [
      "TypeScript frontend component architecture",
      "REST & realtime API consumption",
      "Responsive CSS & modern layout techniques",
    ],
    skillGaps: [
      "Database indexing, query optimization & transaction isolation",
      "Distributed caching patterns (Redis, Edge CDN stale-while-revalidate)",
      "Automated integration & load testing at scale",
    ],
    typicalFirstSteps: [
      "Implement a real-time state synchronization feature using WebSockets / SSE",
      "Profile and eliminate render bottlenecks in a complex React dashboard",
      "Review systems architecture with an Engineering Director",
    ],
    projectsToTry: [
      {
        title: "Real-time Collaboration Engine",
        description: "Build an optimistic UI state engine with offline conflict resolution.",
        timeframe: "2 weeks",
      },
      {
        title: "High-Performance Edge API Proxy",
        description: "Deploy a rate-limited edge worker with streaming response pipelines.",
        timeframe: "1 week",
      },
    ],
    mentorIds: ["mentor-kabir", "mentor-ananya"],
    learningPlanSlug: "se-30-day-foundation",
    salaryRange: "₹20L - ₹50L+",
    demandTrend: "+31% demand for full-stack system generalists",
  },
  {
    id: "path-ai",
    slug: "ai-systems-engineering",
    title: "AI & Systems Engineering",
    category: "Data & AI",
    fitScore: 74,
    fitLevel: "Worth Exploring",
    tagline: "Harness modern LLMs, autonomous agent loops, and multimodal intelligence to build transformative products.",
    description:
      "The frontier of AI applications requires engineers who understand both model mechanics and deterministic product software. This path places you directly at the frontier.",
    whyFit: [
      "Curiosity about prompt orchestration, structured output, and agentic workflows",
      "Strong interest in building intelligence layers on top of user workflows",
    ],
    currentStrengths: [
      "Structured prompt engineering & schema validation",
      "Frontend integration with streaming AI responses",
    ],
    skillGaps: [
      "RAG architecture, vector embeddings & hybrid lexical search",
      "Evals pipeline design & model latency optimization",
      "Agent memory retention & token cost economics",
    ],
    typicalFirstSteps: [
      "Build an autonomous tool-calling agent with structured validation",
      "Benchmark retrieval accuracy across chunking strategies",
      "Review agent architectures with an AI research engineer",
    ],
    projectsToTry: [
      {
        title: "Autonomous Research Agent",
        description: "Build an agent that executes web search, synthesizes findings, and emits citations.",
        timeframe: "2 weeks",
      },
    ],
    mentorIds: ["mentor-ananya"],
    learningPlanSlug: "ai-30-day-foundation",
    salaryRange: "₹24L - ₹60L+",
    demandTrend: "+68% surge in applied AI product roles",
  },
];

export const SKILL_PROFILES: SkillProfile[] = [
  {
    category: "Technical Architecture",
    score: 84,
    level: "Advanced",
    subskills: [
      { name: "Frontend Architecture & React", score: 92 },
      { name: "API Design & Contracts", score: 85 },
      { name: "Database & Data Modeling", score: 76 },
      { name: "Performance & Optimizations", score: 83 },
    ],
    nextLever: {
      skill: "Product Analytics & Instrumentation",
      reason: "Pairing deep technical ability with quantitative user telemetry unlocks high-leverage product decisions.",
      expectedImpact: "+35% stronger signal for Senior PM and Technical Lead transitions",
      actionableStep: "Set up Mixpanel/PostHog tracking on an active project and define a North Star funnel.",
    },
  },
  {
    category: "Product & Strategy",
    score: 76,
    level: "Practitioner",
    subskills: [
      { name: "User Journey Mapping", score: 82 },
      { name: "Problem Definition & Scoping", score: 79 },
      { name: "Opportunity Assessment", score: 74 },
      { name: "Monetization & Pricing", score: 68 },
    ],
    nextLever: {
      skill: "Executive PRD Crafting",
      reason: "Turning intuition into tight, defensible 1-page specs drastically accelerates team alignment.",
      expectedImpact: "Immediate credibility boost in mentor reviews and interview loops",
      actionableStep: "Write a PRD deconstructing FLOUNA's mentor matching algorithm.",
    },
  },
  {
    category: "Design & Interaction",
    score: 72,
    level: "Practitioner",
    subskills: [
      { name: "Visual Hierarchy & Typography", score: 88 },
      { name: "Design Systems & Tokens", score: 80 },
      { name: "Micro-interactions & Motion", score: 70 },
      { name: "Accessibility & Ergonomics", score: 65 },
    ],
    nextLever: {
      skill: "Motion Choreography (Framer Motion)",
      reason: "Elevating UI from static pages to living intelligence workspaces commands luxury product appeal.",
      expectedImpact: "Differentiates portfolio from standard template builders",
      actionableStep: "Add staggered enter transitions to your dashboard cards.",
    },
  },
  {
    category: "Communication & Influence",
    score: 68,
    level: "Foundational",
    subskills: [
      { name: "Written Articulation", score: 78 },
      { name: "Active Listening & Inquiry", score: 72 },
      { name: "Stakeholder Negotiation", score: 60 },
      { name: "Public Presentation", score: 62 },
    ],
    nextLever: {
      skill: "1-on-1 Mentor Inquiry Framework",
      reason: "Asking high-precision questions during mentor sessions 3x the actionable takeaways.",
      expectedImpact: "Converts mentor conversations into active sponsors and career champions",
      actionableStep: "Draft 3 challenge-specific questions before your next mentor session.",
    },
  },
];

export const MENTORS: Mentor[] = [
  {
    id: "mentor-maya",
    name: "Maya Sharma",
    role: "Staff Product Manager",
    company: "Stripe",
    matchScore: 94,
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&h=300&fit=crop&crop=faces&q=80",
    initials: "MS",
    bio: "Ex-Google, now leading payments infrastructure at Stripe. Passionate about helping engineers transition into product leadership.",
    whyRecommended: "Ideal match because you are exploring Product Management with a strong engineering and systems background.",
    experienceYears: 9,
    domains: ["Product Strategy", "FinTech", "Eng-to-PM Transition", "Roadmapping"],
    availability: "Available this week",
    featuredInsight: "Great PMs don't predict the future; they remove ambiguity so engineers can build with conviction.",
    rating: 4.98,
    sessionsCompleted: 142,
  },
  {
    id: "mentor-rohan",
    name: "Rohan Mehta",
    role: "Head of Product Design",
    company: "Linear",
    matchScore: 91,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=faces&q=80",
    initials: "RM",
    bio: "Focusing on ultra-fast craft, design tokens, and keyboard-first productivity software. Mentored 80+ designers globally.",
    whyRecommended: "Recommended because of your interest in high-craft editorial interfaces and micro-interaction polish.",
    experienceYears: 11,
    domains: ["Design Systems", "Interaction Design", "Figma Architecture", "Portfolio Review"],
    availability: "2 slots left",
    featuredInsight: "Polish is not something you add at the end; it is respect for the user woven into every token.",
    rating: 5.0,
    sessionsCompleted: 98,
  },
  {
    id: "mentor-ananya",
    name: "Dr. Ananya Iyer",
    role: "Principal AI Engineer",
    company: "Google DeepMind",
    matchScore: 88,
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&h=300&fit=crop&crop=faces&q=80",
    initials: "AI",
    bio: "Leading agentic orchestration and multimodal reasoning systems. Advises high-growth startups on applied AI roadmaps.",
    whyRecommended: "Strong match for structuring autonomous LLM workflows and evaluation frameworks.",
    experienceYears: 8,
    domains: ["AI Orchestration", "Agentic Workflows", "LLM Evals", "System Architecture"],
    availability: "Next available Mon",
    featuredInsight: "Treat prompt engineering like system design: validate contracts, enforce invariants, and expect stochasticity.",
    rating: 4.96,
    sessionsCompleted: 76,
  },
  {
    id: "mentor-kabir",
    name: "Kabir Sen",
    role: "Director of Engineering",
    company: "Razorpay",
    matchScore: 85,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=faces&q=80",
    initials: "KS",
    bio: "Scaled backend infrastructure to 50M+ daily transactions. Mentors senior engineers aiming for Staff/Principal benchmarks.",
    whyRecommended: "Recommended for sharpening distributed systems architecture and high-scale performance engineering.",
    experienceYears: 13,
    domains: ["Distributed Systems", "Engineering Leadership", "High-Scale Architecture", "System Design"],
    availability: "Available this week",
    featuredInsight: "Simplicity in architecture is the hardest thing to achieve, but it is the only thing that scales.",
    rating: 4.97,
    sessionsCompleted: 115,
  },
  {
    id: "mentor-priya",
    name: "Priya Nambiar",
    role: "Product Growth Lead",
    company: "Notion",
    matchScore: 89,
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop&crop=faces&q=80",
    initials: "PN",
    bio: "Specializes in product-led growth (PLG), viral loops, and community-driven user adoption.",
    whyRecommended: "Great fit for mastering quantitative product experimentation and growth mechanics.",
    experienceYears: 7,
    domains: ["Product Growth", "PLG", "Experimentation", "User Onboarding"],
    availability: "2 slots left",
    featuredInsight: "The best growth loops feel like utility to the user, not marketing to the viewer.",
    rating: 4.95,
    sessionsCompleted: 64,
  },
];

export const DEFAULT_LEARNING_PLAN: LearningPlan = {
  id: "plan-pm-30",
  pathSlug: "product-management",
  pathTitle: "Product Management Foundations & Case Craft",
  targetGoal: "Transition into Associate/Mid-level Product Management with a defensible portfolio and mentor validation.",
  durationDays: 30,
  totalTasks: 16,
  completedTasks: 11,
  weeks: [
    {
      weekNumber: 1,
      phase: "01 DISCOVER",
      title: "Problem Space & Market Signal",
      objective: "Develop an intuition for spotting unmet user needs and structuring market hypotheses.",
      milestone: "Published 1-page Problem Brief on an existing workflow inefficiency.",
      tasks: [
        {
          id: "t-1",
          title: "Audit 3 daily workflows and log points of friction & user fatigue",
          completed: true,
          estimatedHours: 4,
          resourceTitle: "The Anatomy of High-Leverage Problems",
          resourceType: "Framework",
        },
        {
          id: "t-2",
          title: "Conduct 2 informal user interviews around a specific pain point",
          completed: true,
          estimatedHours: 3,
          resourceTitle: "The Mom Test Interview Script",
          resourceType: "Framework",
        },
        {
          id: "t-3",
          title: "Synthesize findings into a defensible Problem Statement",
          completed: true,
          estimatedHours: 2,
          resourceTitle: "Structuring 1-Page Problem Briefs",
          resourceType: "Article",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "02 LEARN",
      title: "Metrics, Metrics Instrumentation & Analytics",
      objective: "Master defining North Star metrics, input metrics, and counter-metrics.",
      milestone: "Complete metrics hierarchy diagram for a SaaS product.",
      tasks: [
        {
          id: "t-4",
          title: "Map North Star vs Input Metrics for FLOUNA's mentor match engine",
          completed: true,
          estimatedHours: 4,
          resourceTitle: "Amplitude North Star Playbook",
          resourceType: "Framework",
        },
        {
          id: "t-5",
          title: "Practice SQL query writing for funnel drop-off calculation",
          completed: true,
          estimatedHours: 5,
          resourceTitle: "SQL for Product Analytics",
          resourceType: "Project",
        },
        {
          id: "t-6",
          title: "Define 3 counter-metrics to safeguard user experience",
          completed: true,
          estimatedHours: 2,
          resourceTitle: "Goodhart's Law in Product Metrics",
          resourceType: "Article",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "03 BUILD",
      title: "PRD Crafting & Spec Delivery",
      objective: "Author a complete, production-grade Product Requirement Document with edge-cases.",
      milestone: "Drafted 4-page end-to-end PRD ready for mentor review.",
      tasks: [
        {
          id: "t-7",
          title: "Draft User Personas, User Stories, and Acceptance Criteria",
          completed: true,
          estimatedHours: 5,
          resourceTitle: "Modern PRD Template (Linear Style)",
          resourceType: "Framework",
        },
        {
          id: "t-8",
          title: "Map edge-cases: error states, empty states, and offline behavior",
          completed: true,
          estimatedHours: 3,
          resourceTitle: "Designing For Edge Cases",
          resourceType: "Article",
        },
        {
          id: "t-9",
          title: "Create low-fidelity wireframes to accompany technical specs",
          completed: true,
          estimatedHours: 4,
          resourceTitle: "Rapid Wireframing in Figma",
          resourceType: "Project",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "04 CONNECT",
      title: "Mentor Review & Strategic Polish",
      objective: "Put your PRD in front of senior product leaders, incorporate feedback, and practice defensibility.",
      milestone: "Completed 1:1 mentor critique session with verified feedback.",
      tasks: [
        {
          id: "t-10",
          title: "Book 1:1 session with Maya Sharma (Staff PM @ Stripe)",
          completed: true,
          estimatedHours: 1,
          resourceTitle: "Mentor Review Prep Guide",
          resourceType: "Discussion",
        },
        {
          id: "t-11",
          title: "Incorporate critique on monetization and engineering trade-offs",
          completed: true,
          estimatedHours: 4,
          resourceTitle: "Iterative Spec Refinement",
          resourceType: "Project",
        },
        {
          id: "t-12",
          title: "Publish final polished case study on personal portfolio",
          completed: false,
          estimatedHours: 3,
          resourceTitle: "Editorial Case Study Formatting",
          resourceType: "Article",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "05 APPLY",
      title: "Strategic Execution & Interview Readiness",
      objective: "Prepare for product sense, execution, and behavioral interview loops.",
      milestone: "Completed 2 mock product design and execution interviews.",
      tasks: [
        {
          id: "t-13",
          title: "Practice 5 classic Product Sense questions with timed breakdowns",
          completed: false,
          estimatedHours: 6,
          resourceTitle: "CIRCLES Method Deep Dive",
          resourceType: "Framework",
        },
        {
          id: "t-14",
          title: "Refine behavioral STAR stories highlighting leadership without authority",
          completed: false,
          estimatedHours: 4,
          resourceTitle: "STAR Story Matrix",
          resourceType: "Article",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "06 REFLECT",
      title: "Growth Retrospective & Next Chapter",
      objective: "Reflect on 30-day growth, update FLOUNA skill profile, and choose next milestone.",
      milestone: "FLOUNA AI updated with verified progress & next horizon goals.",
      tasks: [
        {
          id: "t-15",
          title: "Conduct personal retrospective on strengths discovered and remaining gaps",
          completed: false,
          estimatedHours: 2,
          resourceTitle: "30-Day Growth Retrospective",
          resourceType: "Discussion",
        },
        {
          id: "t-16",
          title: "Lock in next quarter lever with FLOUNA AI orchestrator",
          completed: false,
          estimatedHours: 1,
          resourceTitle: "FLOUNA Goal Locking",
          resourceType: "Framework",
        },
      ],
    },
  ],
};

export const DEFAULT_JOURNEY_PROGRESS: JourneyProgress = {
  overallPercentage: 72,
  activePathTitle: "Product Management",
  currentFocus: "PRD Crafting & Mentor Review",
  completedTasksCount: 11,
  totalTasksCount: 16,
  streakDays: 14,
  recentActivity: [
    { date: "Today, 4:30 PM", title: "Completed Mentor Feedback Integration", type: "mentor" },
    { date: "Yesterday", title: "Added Product Analytics to Skill Profile", type: "skill" },
    { date: "3 days ago", title: "Finished Week 3: PRD Crafting Spec", type: "task" },
    { date: "1 week ago", title: "Explored Path: Product Management", type: "path" },
  ],
  proactiveInsights: [
    "You've completed 4 high-leverage tasks this week with 100% consistency.",
    "Your strongest emerging signal is Product Thinking (+14% over baseline).",
    "You are ready for your next 1:1 mentor review with Maya Sharma.",
    "Next highest-impact lever: Publish your polished Case Study.",
  ],
  nextBestMove: {
    title: "Publish Case Study Portfolio",
    description: "Your PRD on the intelligent notification engine is 95% complete. Publish it to unlock mentor recommendation letters.",
    actionLabel: "Complete Task 12",
    actionHref: "/journey",
  },
};
